all: selectionSort palindrome

selectionSort: selectionSort.cpp headers.h functions.cpp
	g++ -o selectionSort selectionSort.cpp -Wall -std=c++11

palindrome: palindrome.cpp
	g++ -o palindrome palindrome.cpp -Wall -std=c++11